### ISSUE TITLE
Wrong order of Push and Kaniko steps in Maven app build pipeline cause unnecessary jar in docker image

### ISSUE THREAD

**Issue by n-g-work** [epam/edp-tekton#8]
**Describe the bug**

Tekton pipeline for Maven application build has Push (mvn deploy) step before Kaniko step.
This causes creation of unnecessary artifacts (for example *-sources.jar) and copying them into docker image.
Jenkins build pipelines in EDP v2.12 had Kaniko step before Push.

As a workaround a `.dockerignore` file can be placed into the project's root directory or deployable module directory. The latter can be confusing.

**To Reproduce**

#### What did you do?

1. Create an Maven application project with sources plugin set up like this:
```
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>${maven-source-plugin.version}</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <phase>verify</phase>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

2. Add the application to EDP and start an application build pipeline.
3. Pull the image from image registry, run it and check what's inside.

#### What did you expect to see?

Only the deployable *.jar file(s).

#### What did you see instead? Under which circumstances?

The *-sources.jar file(s) along with the deployable *.jar file(s).

**Kubernetes cluster type:**

AWS EKS v1.24

`$ operator-sdk version`

Not applicable.

`$ go version`

Not applicable.

`$ kubectl version`

Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.24.13-eks-0a21954

**Comment by YevheniiPokhvalii** [comment]
Hi @n-g-work ,

The order of Push and Kaniko steps are not connected with the resulting .jar files that appear in the Docker image.
The Push step just deploys everything what's in the 'target' folder after the Java application build to Nexus.
In turn, the Kaniko step takes the Dockerfile commands and pushes everything to the registry according to those instructions.

You can examine our pipelines here: https://github.com/epam/edp-tekton/blob/v0.5.0/charts/pipelines-library/templates/pipelines/_common_java_maven.yaml

We intentinonaly do not include any sort of file ignores in our Pipelines and Tasks since each unique application can  produce different build results.

Threre are several options to avoid unnecessary .jar files to be included into the Docker image:
1. It's .dockerignore like you already mentioned in this issue.
2. The COPY instruction can be modified in the Dockerfile directly.
3. It's also possible to ingnore files via pom.xml file.

**Comment by n-g-work** [comment]
Hi @YevheniiPokhvalii,

I can't disagree that using a `.dockerignore` file is a solution. I have only one problem with this.
It is considered a best practice to place `.dockerignore` file in the root directory of a project, and currently the pipeline ignores it in case of a Maven multimodule project.
For multimodule projects the file must be placed into the folder which corresponds to the value in the `<deployable.module>` tag. And exactly this file location requirement is confusing.

I would consider the issue resolved if the pipeline takes into account the `.dockerignore` file in the project's root directory.

**Comment by YevheniiPokhvalii** [comment]
@n-g-work I see your point.

I experimented a little bit and came up with two solutions.

1. Use `Dockerfile.dockerignore` instead of `.dockerignore` with this content:
```
target/*-sources.jar
```
This file is picked up by the Kaniko runtime along with the path to the Dockerfile.

2. The second solution is to modify `java-maven-springboot-multimodule-impl/pom.xml` and add a custom output folder like it's described here: https://maven.apache.org/plugins/maven-source-plugin/examples/configureplugin.html

```
              <configuration>
                <outputDirectory>target/sources</outputDirectory>
              </configuration>
```

Feel free to check my repo here: https://github.com/YevheniiPokhvalii/java-maven-java8-multimodule
